# ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".

import json
from setuptools import setup

kwargs = json.loads(
    """
{
    "name": "projen_template",
    "python_requires": ">=3.6",
    "author": "DeadlySquad13",
    "author_email": "46250621+DeadlySquad13@users.noreply.github.com",
    "version": "0.1.0"
}
"""
)

setup(**kwargs)
